fix/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^progress/',include('progress.urls',namespace='progress')),
    url(r'^document/',include('document.urls',namespace='document')),
    url(r'^review/',include('review.urls',namespace='review')),
    url(r'^notification/',include('notification.urls',namespace='notification')),
    url(r'^department/',include('department.urls',namespace='department')),
    url(r'^',include('universal.urls',namespace='universal')),
    url(r'^dULANniyVhTiqu9Q3T7FgJ72hkYDo5mdoNzIh85CokLmRY0ghn1SdhvuRPwiggjFdfDoWkYRU2hBA3apgLaS0v5tXNKBtnuDI6oE/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notification/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth.decorators import login_required, permission_required
urlpatterns = [
        url(r'^notification_list/$',views.NotificationListView.as_view(), name='list_notification'),
        url(r'^create_notification/$',permission_required('notification.can_add_notification')(views.NotificationCreateView.as_view()), name='create_notification'),
        url(r'^edit_notification/(?P<pk>\d+)/$',permission_required('notifications.can_change_notification')(views.NotificationUpdateView.as_view()), name='edit_notification'),
        url(r'^delete_notification/(?P<pk>\d+)/$',permission_required('notifications.can_delete_review')(views.NotificationDeleteView.as_view()), name='delete_review'),
]

notification/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Notification(models.Model):
    title = models.CharField(max_length=255, unique=True, blank=False)
    content = models.TextField(blank=False)
    added_on = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)

    @models.permalink
    def get_absolute_url(self):
        return 'notification:home', (self.slug,)

    def __str__(self):
        return '{}'.format(self.title)

notification/views.py
from django.shortcuts import render
from django.views.generic import (CreateView, ListView,
    DetailView, DeleteView, UpdateView)
# Create your views here.
from .models import Notification
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required


class NotificationCreateView(CreateView):
    model = Notification
    fields = ['title','content']
    success_url = reverse_lazy('notification:list_notification')

class NotificationListView(ListView):
    context_object_name = "notifications"
    model = Notification


class NotificationUpdateView(UpdateView):
    model = Notification
    fields = ['title','content']
    success_url = reverse_lazy('accounts:dashboard')


class NotificationDeleteView(DeleteView):
    model = Notification
    success_url = reverse_lazy('accounts:dashboard')

templates/notification/notification_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Notification{% endblock %}
{% block content %}
    <form action="." method="POST">
      {% if perms.notifcation.can_add_notifcation %}
      {% csrf_token %}
      {{ form.as_p }}
      <p><input type="submit" class="btn btn-danger" value="Delete"></p>
      {% endif %}
{% endblock %}

templates/notification/notification_detail.html
{% extends 'base.html' %}
{% block title %}Notification{% endblock %}
{% block content %}
<div class="notification-content"/>
    <h1>{{ notification.title }}</h1>
    <p>{{ notification.content }}</p>
    <p><i>{{ notification.added_on }}</i></p>
</div>
<div id="modify">
      {% if perms.notification.can_add_notification %}
        <a href="{% url 'notification:create_notification' %}" class="btn btn-primary">Add Notification</a>
          {% endif %}

      {% if perms.notification.can_change_notification %}
            <a href="{% url 'notification:edit_notification' %}" class="btn btn-primary">Edit</a>
              {% endif %}
            {% if perms.notification.can_delete_notification %}
            <a href="{% url 'notification:delete_notification' %}" class="btn btn-danger">Delete</a>
              {% endif %}
</div>
{% endblock %}

templates/notification/notification_form.html
{% extends 'base.html' %}
{% block title %}Notification{% endblock %}
{% block content %}
<div class="spacer-big"></div>
<hr>
<div class="spacer-big"></div>
    <form action="." method="POST">
      {% if perms.notification.can_add_notification %}
      {% csrf_token %}
      {{ form.as_p }}
      <p><input type="submit" class="btn btn-primary" value="Add"></p>
      {% endif %}
<div class="spacer-big"></div>
<hr>
<div class="spacer-big"></div>
{% endblock %}

templates/notification/notification_list.html
{% extends 'base.html' %}
{% block title %}Notification{% endblock %}
{% block content %}
<div class="spacer-big"></div>
<hr>
<div class="spacer-big"></div>

            <h4 class="align-center"><strong>Notification</strong></h4>

<div class="column-section boxed-spaced adapt-height vertical-center clearfix">
    <div class="column one-third testimonial">
        <div class="testimonial-content">
          {% for notification in notifications %}
            <h4>{{ notification.title }}</h4>
            <blockquote>{{ notification.content }}</blockquote>
            <p>{{ notification.added_on }}</p>
            <h5 class="testimonial-name">{{ notification.notification_by }}</h5>
            <h6 class="testimonial-meta subtitle-1">{{ notification.notification_by.department }}</h6>
            {% endfor %}
        </div>
        <div class="testimonial-add">

          {% if perms.notification.can_add_notification %}
          <a href="{% url 'notification:create_notification' %}" class="btn btn-primary">Add notification</a>
            {% endif %}
        </div>
    </div>

</div> <!-- END .column-section -->
            <div class="spacer-big"></div>
<hr>
<div class="spacer-big"></div>





{% endblock %}