accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (login,logout,logout_then_login,
                                        password_change, password_change_done,
                                        password_reset, password_reset_done,
                                        password_reset_confirm,
                                         password_reset_complete)
from . import views

urlpatterns = [
    url(r'^$',views.dashboard,name='dashboard'),
    #user registration
    url(r'^register/$', views.register, name='register'),
    # url(r"login/$", views.user_login, name="login"),
    url(r"login/$", login, name="login"),
    url(r"logout/$",logout, {'next_page': 'universal:home'}, name="logout"),
    url(r"logout-then-login/$",logout_then_login, name="logout_then_login"),
    # change password
    url(r'password-change/', password_change, name='password_change'),
    url(r'password-change/done/$', password_change_done, name='password_change_done'),
    # restore apssword urls
    url(r'password/reset/',password_reset,name='password_reset'),
    url(r'password/reset/done/$',password_reset_done,name='password_reset_done'),
    url(r'password/reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/'
        ,password_reset_confirm,name='password_reset_confirm'),
    url(r'password/reset/complete/$',password_reset_complete,name='password_reset_complete'),
    # user view urls
    url(r'^users/$',views.user_list,name='user_list'),
    url(r'^users/(?P<pk>\d+)/$',views.user_detail,name='user_detail'),
]

fix/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^progress/',include('progress.urls',namespace='progress')),
    url(r'^document/',include('document.urls',namespace='document')),
    url(r'^review/',include('review.urls',namespace='review')),
    url(r'^notification/',include('notification.urls',namespace='notification')),
    url(r'^department/',include('department.urls',namespace='department')),
    url(r'^',include('universal.urls',namespace='universal')),
    url(r'^dULANniyVhTiqu9Q3T7FgJ72hkYDo5mdoNzIh85CokLmRY0ghn1SdhvuRPwiggjFdfDoWkYRU2hBA3apgLaS0v5tXNKBtnuDI6oE/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

progress/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth.decorators import login_required, permission_required
urlpatterns = [
        url(r'progress_list/$',views.ProgressListView.as_view(), name='list_progress'),
        url(r'create_progress/$',permission_required('progress.can_add_progress')(views.ProgressCreateView.as_view()), name='create_progress'),
        url(r'edit_progress/(?P<pk>\d+)/$',permission_required('progresss.can_change_progress')(views.ProgressUpdateView.as_view()), name='edit_progress'),
        url(r'delete_progress/(?P<pk>\d+)/$',permission_required('progresss.can_delete_review')(views.ProgressDeleteView.as_view()), name='delete_review'),
]

review/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth.decorators import login_required, permission_required
urlpatterns = [
        url(r'^review_list/$',views.ReviewListView.as_view(), name='list_review'),
        url(r'^create_review/$',permission_required('review.can_add_review')(views.ReviewCreateView.as_view()), name='create_review'),
        url(r'^edit_review/(?P<pk>\d+)/$',permission_required('reviews.can_change_review')(views.ReviewUpdateView.as_view()), name='edit_review'),
        url(r'^delete_review/(?P<pk>\d+)/$',permission_required('reviews.can_delete_review')(views.ReviewDeleteView.as_view()), name='delete_review'),
]

accounts/models.py
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
    Group
)
from django.db import models
from django.utils import timezone
from department.models import Department
from review.models import Review
from django.conf import settings

from django.core.urlresolvers import reverse

from django.core.validators import RegexValidator

EMAIL_REGEX = '^[a-z0-9](\.?[a-z0-9]){5,}@aiesec\.net$'
USERNAME_REGEX = '^[a-zA-Z0-9.@+_]*$'

class UserManager(BaseUserManager):
    def create_user(self, email, username, display_name=None, password=None):
        if not email:
            raise ValueError("Users must have an email address")
        if not display_name:
            display_name = username

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            display_name=display_name,
            department=Department.objects.get(id=1),
            group = Group.objects.get(pk=3)

        )
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, username, display_name, password):
        user = self.create_user(
            email,
            username,
            display_name,
            password
        )
        user.is_staff = True
        user.is_superuser = True
        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True,max_length=255,
    blank=False,
     validators=[RegexValidator( regex = EMAIL_REGEX,
     message='Email must be a valid @aiesec.net',
     code='invalid email')])
    username = models.CharField(max_length=40,blank=False,
    unique=True,
    validators=[RegexValidator( regex = USERNAME_REGEX,
     message='username must be alphanumeric or contain ., @, +, _',
     code='invalid_username')])
    first_name = models.CharField(max_length=100, blank=False)
    last_name = models.CharField(max_length=100, blank=False)
    display_name = models.CharField(max_length=140)
    bio = models.TextField(max_length=500, blank=True, default="")
    avatar = models.ImageField(blank=True, null=True)
    date_joined = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE,
                            default=3,
                            related_name="member_of")
    review = models.ManyToManyField('self', through=Review,
    related_name='testinomial', symmetrical=False)


    objects = UserManager()

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["display_name", "email"]

    def __str__(self):
        return "{}".format(self.username)

    def get_short_name(self):
        return self.display_name

    def get_long_name(self):
        return "{} (@{})".format(self.display_name, self.username)

    def get_full_name(self):
        return "{} {}".format(self.first_name, self.last_name)

    def get_absolute_url(self):
        return reverse('accounts:user_detail', args=[self.id])

progress/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Progress(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,related_name='progress_of')
    quality1 = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(100)])
    quality2 = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(100)])
    quality3 = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(100)])
    quality4 = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(100)])
    quality5 = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(100)])
    quality6 = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(100)])
    quality7 = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(100)])
    quality8 = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(100)])

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.conf import settings
from .models import User


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

# # class UserCreateForm(UserCreationForm):
#     class Meta:
#         fields = ("username", "email","display_name","first_name",
#         "last_name","password1", "password2", "department")
#         model = get_user_model()

#     def clean_password2(self):
#         cd = self.cleaned_data
#         if cd['password1'] != cd['password2']:
#             raise forms.ValidationError('Passwords don\'t match.')
#         return cd['password2']

#     def __init__(self, *args, **kwargs):
#         super(UserCreateForm, self).__init__(*args, **kwargs)
#         self.fields["username"].label = "Display name"
#         self.fields["email"].label = "Email address"

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)

    class Meta:
        model = get_user_model()
        fields = ("username", "email","display_name","first_name",
        "last_name","password", "password2", "department")
        

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password']

accounts/views.py
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

from .models import User
from review.models import Review
from progress.models import Progress
from . import forms
from .forms import LoginForm, UserRegistrationForm

from django.views.decorators.csrf import csrf_protect

@login_required
def dashboard(request):
    return render(request,
                'accounts/dashboard.html',
                {'section':'dashboard'})

@csrf_protect
def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(
                user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            return render(request,
                          'accounts/register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request,
                  'accounts/register.html',
                  {'user_form': user_form})

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            clean_data = form.cleaned_data
            user = authenticate(username=clean_data['username'],
                                    password=clean_data['password'])
            if user is not None:
                if user.is_active:
                    login(request,user)
                    return HttpResponse('Authenticated')
                else:
                    return HttpResponse('Disabled')
            else:
                return HttpResponse('Invalid Login')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form':form})

class LoginView(generic.FormView):
    form_class = AuthenticationForm
    success_url = reverse_lazy("document:upload")
    template_name = "accounts/dashboard.html"

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(self.request, **self.get_form_kwargs())

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super().form_valid(form)


class LogoutView(generic.RedirectView):
    url = reverse_lazy("home")

    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)


# class SignUp(generic.CreateView):
#     form_class = forms.UserCreateForm
#     success_url = reverse_lazy("login")
#     template_name = "accounts/signup.html"
#
#

@login_required
def user_list(request):
    users = User.objects.filter(is_active=True)
    return render(request, 'accounts/user/list.html',
                            {'section':'people', 'users': users})

@login_required
def user_detail(request,pk):
    profile_user = get_object_or_404(User, pk=pk, is_active=True)
    reviews = Review.objects.filter(review_of=profile_user)
    progress_list = Progress.objects.filter(user=profile_user)
    return render(request, 'accounts/user/detail.html',
                            {'section':'people',
                            'pk':pk,
                            'profile_user':profile_user,
                            'reviews':reviews,
                            'progress_list':progress_list})

templates/accounts/dashboard.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}
{% block content %}


{% block css %}
<style type="text/css">


body{
padding-top:120px;
}

  </style>
{% endblock %}
  
  
<h2 style="color:#777">Dashboard</h2>
<h1 >{{ request.user.get_full_name }}</h1>
<div class="spacer-small"></div>

        <section id="hero" class="hero-auto" style="background-color:#03004c">

              <div id="page-title" class="wrapper align-center">
                  <h2 class="uppercase" style="color:#fff"><strong>Your progress so far...</strong></h2>
              </div> <!-- END #page-title -->

          </section>
          <div class="spacer-big"></div>
        <div class="wrapper">

              <div class="column-section clearfix">
                    <div class="progress-bar-item big-bar">
                          <h6 class="progress-name">Quality 1</h6>
                          <div class="progress-bar"><div class="progress-active" style="background-color:#f75067;" data-perc="{{ request.user.progress_of.quality1 }}">
                          <span class="tooltip">{{ request.user.progress_of.quality1 }}%</span></div></div>
                      </div>
                      <div class="spacer-big"></div>

                      <div class="progress-bar-item big-bar">
                          <h6 class="progress-name">Quality 2</h6>
                          <div class="progress-bar"><div class="progress-active" style="background-color:#aa88b6;" data-perc="{{ request.user.progress_of.quality2 }}">
                          <span class="tooltip">{{ request.user.progress_of.quality2 }}%</span></div></div>
                      </div>
                      <div class="spacer-big"></div>

                      <div class="progress-bar-item big-bar">
                          <h6 class="progress-name">Quality 3</h6>
                          <div class="progress-bar"><div class="progress-active" style="background-color:#5e349c;" data-perc="{{ request.user.progress_of.quality3 }}">
                          <span class="tooltip">{{ request.user.progress_of.quality3 }}%</span></div></div>
                      </div>
                      <div class="spacer-big"></div>

                      <div class="progress-bar-item big-bar">
                          <h6 class="progress-name">Quality 4</h6>
                          <div class="progress-bar"><div class="progress-active" style="background-color:#39ab86;" data-perc="{{ request.user.progress_of.quality4 }}">
                          <span class="tooltip">{{ request.user.progress_of.quality4 }}%</span></div></div>
                      </div>
                      <div class="spacer-big"></div>

                       <div class="progress-bar-item big-bar">
                          <h6 class="progress-name">Quality 5</h6>
                          <div class="progress-bar"><div class="progress-active" style="background-color:#a03537;" data-perc="{{ request.user.progress_of.quality5 }}">
                          <span class="tooltip">{{ request.user.progress_of.quality5 }}%</span></div></div>
                      </div>
                  </div>
              </div>

          {% if perms.progress.add_progress %}
          <!-- <a href="{% url 'progress:create_progress' %}" class="btn btn-primary">Edit Progress</a> -->
            {% endif %}
        </div>
    </div>

</div> <!-- END .column-section -->
            <div class="spacer-big"></div>
<hr>
<div class="spacer-big"></div>







<div class="spacer-big"></div>
<hr>
<div class="spacer-big"></div>

        <h4 class="align-center"><strong>Comments by VPs</strong></h4>

<div class="column-section boxed-spaced adapt-height vertical-center clearfix">
<div class="column one-third testimonial">
    <div class="testimonial-content">
      {% for review in reviews %}
        <h4>{{ review.title }}</h4>
        <blockquote>{{ review.content }}</blockquote>
        <h5 class="testimonial-name">{{ review.review_by }}</h5>
        <h6 class="testimonial-meta subtitle-1">{{ review.review_by.department.name }}</h6>
        {% endfor %}
    </div>
    <div class="testimonial-add">

      {% if perms.review.can_add_review %}
      <!-- <a href="{% url 'review:create_review' %}" class="btn btn-primary">Add Review</a> -->
        {% endif %}
    </div>
</div>

</div> <!-- END .column-section -->
        <div class="spacer-big"></div>
<hr>
<div class="spacer-big"></div>


{% block javascript %}
<script type="text/javascript" >
  
  document.getElementById("header").classList.remove("header-transparent");
  document.getElementById("header").classList.remove("transparent-light");
</script>
{% endblock %}


{% endblock %}

templates/accounts/register.html
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}

{% block css %}
<style type="text/css">


body{
padding-top:90px;
}

  </style>
{% endblock %}
<div class="wrapper">
  
  <div class="column-section clearfix">
       <h1>Sign Up for a new Account</h1>

        <div class="column one-half">
        <p>Please, sign up using the following form:</p>
        <form action="." method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          
          <p><input type="submit" value="Sign Up"></p>
        </form>
      </div>
  </div>
</div>
  
  
  {% block javascript %}
<script type="text/javascript" >
  
  document.getElementById("header").classList.remove("header-transparent");
  document.getElementById("header").classList.remove("transparent-light");
</script>
{% endblock %}

{% endblock %}

templates/accounts/register_done.html
{% extends "base.html" %}

{% block title %}SignUp Complete{% endblock %}

{% block content %}
  <h1>Welcome {{ new_user.first_name }}!</h1>
  <p>Your account has been successfully created, and is now to be approved by your VP.</p>
  <p>If you can't login in a days time, try contacting your respective department's VP</p>
  <p>Click <a href="{% url 'universal:home' %}">here</a> to return to the site</p>
{% endblock %}