document/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
            url(r'^$', views.upload, name='upload'),
            url(r'^simple/$', views.simple_upload, name='simple_upload'),
            url(r'^form/$', views.model_form_upload, name='model_form_upload'),
]

fix/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^progress/',include('progress.urls',namespace='progress')),
    url(r'^document/',include('document.urls',namespace='document')),
    url(r'^review/',include('review.urls',namespace='review')),
    url(r'^notification/',include('notification.urls',namespace='notification')),
    url(r'^department/',include('department.urls',namespace='department')),
    url(r'^',include('universal.urls',namespace='universal')),
    url(r'^dULANniyVhTiqu9Q3T7FgJ72hkYDo5mdoNzIh85CokLmRY0ghn1SdhvuRPwiggjFdfDoWkYRU2hBA3apgLaS0v5tXNKBtnuDI6oE/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

document/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.db import models

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.uploaded_by.id, filename)

# Create your models here.
class Document(models.Model):
    title = models.CharField(max_length=255)
    document = models.FileField(upload_to=user_directory_path)
    description = models.TextField(max_length=500)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    uploaded_by = models.ForeignKey(settings.AUTH_USER_MODEL,
    on_delete=models.CASCADE, related_name="uploader")

document/forms.py
from django import forms

from .models import Document


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('title','description', 'document', )
    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(DocumentForm, self).__init__(*args, **kwargs)

document/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.core.files.storage import FileSystemStorage

from .models import Document
from .forms import DocumentForm


def upload(request):
    documents = Document.objects.all()
    return render(request, 'document/upload.html', { 'documents': documents })


def simple_upload(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        return render(request, 'document/simple_upload.html', {
            'uploaded_file_url': uploaded_file_url
        })
    return render(request, 'document/simple_upload.html')


def model_form_upload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user_name = request.user
            obj.save()
            return redirect('home')
    else:
        form = DocumentForm()
    return render(request, 'document/model_form_upload.html', {
        'form': form
    })

templates/document/model_form_upload.html
{% extends 'base.html' %}
{% block title %}Uplaod Form{% endblock %}
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

  <p>Click <a href="{% url 'document:upload' %}">here</a> to see the files</p>
{% endblock %}

templates/document/simple_upload.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Simple Upload{% endblock %}
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>

  {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %}

  <p><a href="{% url 'document:upload' %}">Return to home</a></p>
{% endblock %}

templates/document/upload.html
{% extends 'base.html' %}
{% block title %}Documents{% endblock %}
{% block content %}
  <ul>
    <li>
      <a href="{% url 'document:simple_upload' %}">Simple Upload</a>
    </li>
    <li>
      <a href="{% url 'document:model_form_upload' %}">Model Form Upload</a>
    </li>
  </ul>

  <p>Uploaded files:</p>
  <ul>
    {% for obj in documents %}
      <li>
        <a href="{{ obj.document.url }}">{{ obj.document.name }}</a>
        <small>(Uploaded at: {{ obj.uploaded_at }})</small>
      </li>
    {% endfor %}
  </ul>
{% endblock %}